terraform {
  required_version = ">= 1.0"

  required_providers {
    random = {
      version = "~> 3.0"
    }
  }
}

provider "local" {}
provider "random" {}

locals {
  prefix = "jbt_"
}

# Example resources

# Create a file
resource "local_file" "hello_world" {
  content  = "Hello World!"
  filename = "${path.module}/files/helloworld.txt"
}

resource "local_file" "file1" {
  content  = "Hello World!"
  filename = "${path.module}/files/${local.prefix}${var.filename1}.txt"
}

# Create a random filename using random_pet
resource "random_pet" "filename" {
  length    = 2
  separator = "_"
}

# Create a random integer using random_integer
resource "random_integer" "integer" {
  min = 1000
  max = 10000
}

# Create a file using the pet name and integer
resource "local_file" "random_pet_file" {
  filename = "${path.module}/files/${random_pet.filename.id}.txt"
  content  = "Generated by Terraform (${random_integer.integer.result})"
}

# Output the pet name and integer to the console
output "pet_name" {
  value = random_pet.filename.id
}

output "integer" {
  value = random_integer.integer.result
}
